export {default as Home} from './Home/Home'
export {default as ExplorePhoto} from './ExplorePhoto/ExplorePhoto'
export {default as ExploreVideo} from './ExploreVideo/ExploreVideo'
export {default as SearchPhotos} from './SearchPhotos/SearchPhotos'
export {default as PhotoDetail} from './PhotoDetail/PhotoDetail'
export {default as NotFound} from './NotFound/NotFound'
export {default as AboutPage} from './About/AboutPage'